# -*- coding: utf-8 -*-
"""cnn_classifier_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTSSVPjCPVBzvwurIMCakx9D_oMvNLsR

Imporitng important libraries
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

"""Making a directory for kaggle token"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""downloading dataset directly from kaggle using API"""

!kaggle competitions download -c dogs-vs-cats

"""Unziping datastet"""

!unzip dogs-vs-cats.zip -d dogs-vs-cats.

"""some more unzipping"""

!unzip dogs-vs-cats/train.zip -d train
!unzip dogs-vs-cats/test1.zip -d test

"""Making the separate folder for dog and cat images"""

import os, shutil

os.makedirs('data/train/cats', exist_ok=True)
os.makedirs('data/train/dogs', exist_ok=True)

"""Putting cats images cats folder , doing same for dogs"""

for img in os.listdir('/content/train/train'):
    if img.startswith('cat'):
        shutil.move(os.path.join('train', img), 'data/train/cats')
    else:
        shutil.move(os.path.join('train', img), 'data/train/dogs')

"""ImageDataGenerate wants the data of different classes in different folder so we are doing it"""

train_dir = 'data/train'
test_dir = 'test/test1'

train_datagen = ImageDataGenerator( rescale=1./255,
                                   rotation_range=30,
                                    width_shift_range=0.2,
                                    height_shift_range=0.2,
                                    shear_range=0.2,
                                    zoom_range=0.2,
                                    horizontal_flip=True,
                                    fill_mode='nearest',
                                    validation_split=0.2 # Add validation split here
                                    )

test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),
    batch_size=32,
    class_mode='binary'
)

val_gen = train_datagen.flow_from_directory(
    '/content/data/train',
    target_size=(150, 150),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

from tensorflow.keras import layers, models

"""from tensorflow.keras import layers, models"""

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_gen,
    epochs=10,
    validation_data=val_gen
)

print("hello")

from tensorflow.keras.preprocessing import image
import numpy as np

img_path = 'image.jpg'
img = image.load_img(img_path, target_size=(150, 150))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)
print(prediction[0][0])
if prediction[0][0] > 0.5:
    print("Dog 🐕")
else:
    print("Cat 🐈")

